[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@payloadcms/db-mongodb", "payload"]
  included_files = ["dist/**", "public/**"]

[build.environment]
  NODE_VERSION = "20"
  SHARP_IGNORE_GLOBAL = "true"
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"