[build]
  command = "SKIP_TYPESCRIPT_CHECK=true pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@payloadcms/db-mongodb", "payload"]
  included_files = ["dist/**"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "20"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200